### ISSUE TITLE
How do I create a column like this?

### ISSUE THREAD

**Issue by hermanzh** [saveriomiroddi/spreadbase#1]
Hi, I use your library to create an ods file, but I don't know how do I create this column with one cell like this:

+-----+------+
|____a____|
+-----+-------+
|a1    |a2      |  
+-----+-------+

Thanks in advance!

Regards,Herman

**Comment by hermanzh** [comment]
I mean, how can I merge two cells ?

**Comment by ghost** [comment]
Hello Herman! Let me review the code - I thought nobody would use it :-) I will get back to you in a couple of days!

**Comment by hermanzh** [comment]
OK, Thanks a lot for your quick respond!

**Comment by 64kramsystem** [comment]
Are you going to use the merge only in a horizontal way, or do you require also vertical merging capabilities? Starting with horizontal only would most likely simplify the task.

**Comment by hermanzh** [comment]
![example](https://cloud.githubusercontent.com/assets/8265614/3714025/73549516-1591-11e4-97a0-38ebe5e4f99f.jpg)
Actually I want the style like attached picture, this maybe need both horizontal and vertical merging.
Thanks!

**Comment by 64kramsystem** [comment]
I see. This requires some significant additions, because in the release version, there's not concept of cell styling, which is required.

There was already work in progress code for such functionality.

I will code in the next days and post the updates!

**Comment by hermanzh** [comment]
Got it, thank you!

**Comment by 64kramsystem** [comment]
(3 years after... phew!)

I'm resuming work on this library, but I don't have such feature in a realistic plan, so I'm closing this as won't fix - sorry!
