### ISSUE TITLE
`rubyzip` dependency is too loose

### ISSUE THREAD

**Issue by 64kramsystem** [saveriomiroddi/spreadbase#22]
See:

```
WARNING:  open-ended dependency on rubyzip (>= 1.3.0) is not recommended
  if rubyzip is semantically versioned, use:
    add_runtime_dependency 'rubyzip', '~> 1.3', '>= 1.3.0'
```

**Comment by taichi-ishitani** [comment]
The latest version of rubyzip is `2.3.0` but this version supports Ruby 2.4 or later.
https://rubygems.org/gems/rubyzip
I think it is better that we should drop ruby 2.3 support to use the latest rubyzip.

**Comment by 64kramsystem** [comment]
> The latest version of rubyzip is `2.3.0` but this version supports Ruby 2.4 or later.
> https://rubygems.org/gems/rubyzip
> I think it is better that we should drop ruby 2.3 support to use the latest rubyzip.

Makes sense. Ruby 2.3 has been anyway discontinued long ago.

Thanks! I'm taking care of this in a PR.
