### ISSUE TITLE
Add bigdecimal into gemspec

### ISSUE THREAD

**Issue by taichi-ishitani** [saveriomiroddi/spreadbase#30]
Hi @64kramsystem ,

I got the warning below when using the spreadbase gem with Ruby 3.3.

```
/opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/spreadbase-0.4.0/lib/spreadbase/codecs/open_document_12_modules/encoding.rb:3: warning: bigdecimal was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add bigdecimal to your Gemfile or gemspec. Also contact author of spreadbase-0.4.0 to add bigdecimal into its gemspec.
```

To fix this warning, we need to add the bigdecimal gem to the gemspec. However there is version confliction between spreadbase gem and bigdecimal gem.

* spreadbase: ruby 2.4
    *  https://github.com/64kramsystem/spreadbase/blob/02b760a6e88a133d7919f1f985228bfed703bb5c/spreadbase.gemspec#L11
* bigdecimal: ruby 2.5
    * https://github.com/ruby/bigdecimal/blob/5843c89da40b743225de2a822a6d4030848d972a/bigdecimal.gemspec#L53

**Comment by 64kramsystem** [comment]
Hi! I'll take a look :smile:

**Comment by 64kramsystem** [comment]
Ruby 2.4.0 is EOL; I'll remove support for it.

**Comment by taichi-ishitani** [comment]
Ruby 2.x series has already been EOL so how about changing required ruby version to 3.0?

**Comment by 64kramsystem** [comment]
> Ruby 2.x series has already been EOL so how about changing required ruby version to 3.0?

Hi! Generally, libraries have some users with EOL Ruby versions. However, I'm pretty sure that this it's not the case for this library (:joy:), so I'll follow your advice :blush:

I'll update the library once I'm back from holiday, in a few days :smile:

**Comment by 64kramsystem** [comment]
@taichi-ishitani Hello! I've done all the required updates. Can you test the master version, or do I need to release a new version first? There has been simple but extensive changes, and the CI surely isn't enough to cover all use cases.

**Comment by taichi-ishitani** [comment]
Hi @64kramsystem ,
Thank you!
I've tested the latest spreadbase on my side and found no issues.

**Comment by taichi-ishitani** [comment]
Ruby 3.0 includes bigdecimal 3.0 series but not 3.1 series so I think spreadbase should depend on 3.0 or later.
https://stdgems.org/bigdecimal/#gem-version
https://github.com/64kramsystem/spreadbase/blob/55a8749cf59411e84864719a546a4ed50716a0c2/spreadbase.gemspec#L21

**Comment by 64kramsystem** [comment]
> Ruby 3.0 includes bigdecimal 3.0 series but not 3.1 series so I think spreadbase should depend on 3.0 or later. https://stdgems.org/bigdecimal/#gem-version
> 
> https://github.com/64kramsystem/spreadbase/blob/55a8749cf59411e84864719a546a4ed50716a0c2/spreadbase.gemspec#L21

This is taken care of :smile: - required Ruby is now v3.0 (on master; I'll release the new gem version a bit later).

**Comment by taichi-ishitani** [comment]
What I want to tell is about version of bigdecimal gem.
Ruby 3.0 includes bigdecimal v3.0.0 so I think version requirement of bigdecimal should be like below.

```ruby
s.add_runtime_dependency "bigdecimal", ">= 3.0.0"
```
