### ISSUE TITLE
Add rexml to gemspec

### ISSUE THREAD

**Issue by taichi-ishitani** [saveriomiroddi/spreadbase#38]
rexml has already been a bundled gem from Ruby 3.0.
https://stdgems.org/rexml/#as-bundled-gem

Therefore we should add rexml to gemspec.

**Comment by 64kramsystem** [comment]
> rexml has already been a bundled gem from Ruby 3.0. https://stdgems.org/rexml/#as-bundled-gem
> 
> Therefore we should add rexml to gemspec.

Hi!

Thanks for your inputs, they have been very valuable :smile: 

I've released the a new version of the gem (v0.5.0), with all the changes you've suggested.
