### ISSUE TITLE
Deprecated warnings

### ISSUE THREAD

**Issue by duartemvix** [saveriomiroddi/spreadbase#9]
I've been getting these warnings lately on every instance creation. I guess we could remove the entire constant out of the module.

```
/home/matt/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/spreadbase-0.1.3/lib/spreadbase/helpers/helpers.rb:34: warning: constant ::Fixnum is deprecated
/home/matt/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/spreadbase-0.1.3/lib/spreadbase/codecs/open_document_12_modules/encoding.rb:178: warning: constant ::Fixnum is deprecated
```

**Comment by 64kramsystem** [comment]
Hello! Thanks for opening the issue. I'm surprised that this gem is in use :grimacing:. I'll look into it over this week.

**Comment by duartemvix** [comment]
> Hello! Thanks for opening the issue. I'm surprised that this gem is in use . I'll look into it over this week.

It has come to be very handy. Although this is just a warning I decided to notify you regardless of what you're working on at this moment. Feel free look at whenever you want.

**Comment by 64kramsystem** [comment]
Hello! I've just released a new (patch) version of the gem, which includes, among the changes, a cleanup of all the warnings. Let me known if there is any issue - I haven't been using the gem for a long time, so I'm using a reference the test suite.
